- hosts: localhost
  user: root
  become: false
  connection: local
  
  vars_files:
  # vars for the install server
  - vars/server.yml
  # vars for the client machines to install OS on
  - vars/preseeds.yml

  tasks:
    - name: purge packages
      apt:
        pkg: "{{ item }}" 
        state: absent
        purge: yes
      loop:
        - apache2
        - tftpd-hpa
        - dnsmasq
        - vsftpd

    - name: remove tftp and repo dirs
    loop:
      - "{{ repos.path }}"
      - "{{ tftp.path }}"
    file:
      path: "{{ item }}"
      state: absent

#    - name: удаление ссылок на зеркало пакетов
#      file: path={{ http.link_to_packages_mirror }} state=absent

#    - name: удаление каталога tftp
#      file: path={{ http.path_to_tftp_files }} state=absent
#      when: server_type == 'http'
