#
# © ООО «Лаборатория 50», 2014
#
---
# uninstall server for preseed install OS

- hosts: inst_servers
#  user: root
  connection: local
  sudo: True
  vars_files: ['group_vars/all']

  tasks:
    - name: удаление пакетов
      apt: pkg={{ item }} state=absent purge=yes
      with_items: [apache2, tftpd-hpa, dnsmasq, vsftpd]

#    - name: удаление ссылок на tftp
#      file: path={{ link_to_tftp_files }} state=absent

#    - name: удаление ссылок на зеркало пакетов
#      file: path={{ http.link_to_packages_mirror }} state=absent

#    - name: удаление каталога tftp
#      file: path={{ http.path_to_tftp_files }} state=absent
#      when: server_type == 'http'
