- name: install syslinux-efi
  apt:
    pkg: syslinux-efi
    state: present
  when: uefi

- name: copying boot files
  copy:
    src: "{{ item }}"
    dest: "{{ tftp.path }}"
  with_items:
    - /usr/lib/SYSLINUX.EFI/efi64/syslinux.efi
    - /usr/lib/syslinux/modules/efi64/ldlinux.e64
  when: uefi

- name: remove old PXELinux configs
  file:
    state: absent
    path: "{{ tftp.path }}/pxelinux.cfg"
    
- name: create directory for PXELinux configs
  file:
    path: "{{ tftp.path }}/pxelinux.cfg"
    state: directory
    owner: dnsmasq
    mode: 0755

- name: create default PXELinux config
  template:
    src: tftp.conf.j2
    dest: "{{ tftp.path }}/pxelinux.cfg/default"
    owner: dnsmasq
    mode: 0644
  when:
    dhcp.static_mode is not defined or dhcp.static_mode == false

- name: create PXELinux configs
  template:
    src: tftp.conf.j2
    dest: "{{ tftp.path }}/pxelinux.cfg/01-{{ item.mac.0 | replace(':', '-') | lower }}"
    owner: dnsmasq
    mode: 0644
  loop: "{{ machines_by_mac }}"
  vars:
    preseed: "{{ item.preseed | default(preseeds.standard) }}"
    host: "{{ item }}"
  when: machines_by_mac is defined

# - name: debug
#   template:
#     src: test.j2
#     dest: "{{ tftp.path }}/pxelinux.cfg/01-{{ item.mac.0 | replace(':', '-') | lower }}"
#     owner: dnsmasq
#     mode: 0644
#   loop: "{{ machines_by_mac }}"
#   vars:
#     preseed: "{{ item.preseed | default(preseeds.standard) }}"
#   when: machines_by_mac is defined

    # - { mac: ['BC:24:11:8E:C5:2E'], hostname: astra1, ip: 10.1.2.240, preseed: preseeds.standard }
